version: '3'

services:
  
  simple-web:
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    build: ./server
    depends_on: 
      - db
    environment:
      DB_HOST: db
    volumes:
      - ./server/src:/usr/app/src:z # SELinux workaround 
    ports: 
      - "8080:3001"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_USER: pguser
      POSTGRES_DB: secretdb
    volumes:    
      - ./server/pgdata:/var/lib/postgresql/data:z # SELinux workaround 
    ports:
      - "5432:5432"
